// <auto-generated />
namespace Project_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changetypeofphonenumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetypeofphonenumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202301192231557_change type of phone number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
